"""add copywriting table

Revision ID: 3a016db24d47
Revises: 95e4b7d794d8
Create Date: 2026-06-16 01:27:19.588774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a016db24d47'
down_revision: Union[str, None] = '95e4b7d794d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copywritings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('copywriting_id', sa.String(length=100), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('hooks', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('mode', sa.String(length=20), nullable=True),
        sa.Column('persona', sa.String(length=500), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_copywriting_created_at', 'copywritings', ['created_at'], unique=False)
    op.create_index('idx_copywriting_user_mode', 'copywritings', ['user_id', 'mode'], unique=False)
    op.create_index(op.f('ix_copywritings_copywriting_id'), 'copywritings', ['copywriting_id'], unique=True)
    op.create_index(op.f('ix_copywritings_id'), 'copywritings', ['id'], unique=False)
    op.create_index(op.f('ix_copywritings_user_id'), 'copywritings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copywritings_user_id'), table_name='copywritings')
    op.drop_index(op.f('ix_copywritings_id'), table_name='copywritings')
    op.drop_index(op.f('ix_copywritings_copywriting_id'), table_name='copywritings')
    op.drop_index('idx_copywriting_user_mode', table_name='copywritings')
    op.drop_index('idx_copywriting_created_at', table_name='copywritings')
    op.drop_table('copywritings')
    # ### end Alembic commands ###
