"""initial migration

Revision ID: 95e4b7d794d8
Revises:
Create Date: 2026-06-16 00:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e4b7d794d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(50), nullable=False),
        sa.Column('password_hash', sa.String(255), nullable=False),
        sa.Column('email', sa.String(255), nullable=True),
        sa.Column('quota_balance', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_user_username_email', 'users', ['username', 'email'], unique=False)
    op.create_index('idx_user_active_quota', 'users', ['is_active', 'quota_balance'], unique=False)

    op.create_table('tasks',
        sa.Column('task_id', sa.String(36), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('transcript', sa.Text(), nullable=True),
        sa.Column('outline', sa.Text(), nullable=True),
        sa.Column('timestamps', sa.Text(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_tasks_task_id', 'tasks', ['task_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_is_deleted', 'tasks', ['is_deleted'], unique=False)
    op.create_index('ix_tasks_user_id', 'tasks', ['user_id'], unique=False)
    op.create_index('idx_task_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_task_user_deleted', 'tasks', ['is_deleted'], unique=False)
    op.create_index('idx_task_created_at', 'tasks', ['created_at'], unique=False)

    op.create_table('user_personas',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('persona_description', sa.Text(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_personas_user_id', 'user_personas', ['user_id'], unique=False)
    op.create_index('ix_user_personas_last_used_at', 'user_personas', ['last_used_at'], unique=False)
    op.create_index('idx_persona_user_last_used', 'user_personas', ['user_id', 'last_used_at'], unique=False)

    op.create_table('subscriptions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('topic', sa.String(100), nullable=False),
        sa.Column('description', sa.String(200), nullable=True),
        sa.Column('frequency', sa.String(20), nullable=False, server_default='daily'),
        sa.Column('status', sa.String(20), nullable=False, server_default='active'),
        sa.Column('last_pushed_at', sa.DateTime(), nullable=True),
        sa.Column('next_push_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_topic', 'subscriptions', ['topic'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_next_push_at', 'subscriptions', ['next_push_at'], unique=False)
    op.create_index('idx_subscription_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_index('idx_subscription_next_push', 'subscriptions', ['next_push_at'], unique=False)

    op.create_table('push_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('topic', sa.String(100), nullable=False),
        sa.Column('hot_topic_data', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='new'),
        sa.Column('pushed_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_push_records_id', 'push_records', ['id'], unique=False)
    op.create_index('ix_push_records_subscription_id', 'push_records', ['subscription_id'], unique=False)
    op.create_index('ix_push_records_topic', 'push_records', ['topic'], unique=False)
    op.create_index('ix_push_records_status', 'push_records', ['status'], unique=False)
    op.create_index('ix_push_records_pushed_at', 'push_records', ['pushed_at'], unique=False)
    op.create_index('idx_push_subscription_status', 'push_records', ['subscription_id', 'status'], unique=False)
    op.create_index('idx_push_pushed_at', 'push_records', ['pushed_at'], unique=False)

    op.create_table('token_blacklist',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token_hash', sa.String(64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_revoked', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_blacklist_id', 'token_blacklist', ['id'], unique=False)
    op.create_index('ix_token_blacklist_token_hash', 'token_blacklist', ['token_hash'], unique=True)
    op.create_index('ix_token_blacklist_user_id', 'token_blacklist', ['user_id'], unique=False)
    op.create_index('ix_token_blacklist_expires_at', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index('ix_token_blacklist_is_revoked', 'token_blacklist', ['is_revoked'], unique=False)
    op.create_index('idx_token_blacklist_user_revoked', 'token_blacklist', ['user_id', 'is_revoked'], unique=False)

    op.create_table('contents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content_type', sa.String(20), nullable=False),
        sa.Column('content_id', sa.String(100), nullable=False),
        sa.Column('hot_topic_id', sa.String(100), nullable=True),
        sa.Column('hot_topic_title', sa.String(500), nullable=True),
        sa.Column('hot_topic_source', sa.String(50), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(500), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('mode', sa.String(20), nullable=True),
        sa.Column('persona', sa.String(500), nullable=True),
        sa.Column('platform', sa.String(20), nullable=True),
        sa.Column('style', sa.String(20), nullable=True),
        sa.Column('is_processed', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contents_id', 'contents', ['id'], unique=False)
    op.create_index('ix_contents_content_type', 'contents', ['content_type'], unique=False)
    op.create_index('ix_contents_content_id', 'contents', ['content_id'], unique=False)
    op.create_index('ix_contents_hot_topic_id', 'contents', ['hot_topic_id'], unique=False)
    op.create_index('ix_contents_user_id', 'contents', ['user_id'], unique=False)
    op.create_index('ix_contents_is_processed', 'contents', ['is_processed'], unique=False)
    op.create_index('ix_contents_created_at', 'contents', ['created_at'], unique=False)
    op.create_index('idx_content_user_type', 'contents', ['user_id', 'content_type'], unique=False)
    op.create_index('idx_content_topic', 'contents', ['hot_topic_id'], unique=False)
    op.create_index('idx_content_processed', 'contents', ['is_processed'], unique=False)
    op.create_index('idx_content_created_at', 'contents', ['created_at'], unique=False)

    op.create_table('hot_topic_trends',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('hot_topic_id', sa.String(100), nullable=False),
        sa.Column('hot_topic_title', sa.String(500), nullable=True),
        sa.Column('hot_topic_source', sa.String(50), nullable=True),
        sa.Column('heat_score', sa.Integer(), nullable=True),
        sa.Column('trend_direction', sa.String(20), nullable=True),
        sa.Column('recorded_at', sa.DateTime(), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hot_topic_trends_id', 'hot_topic_trends', ['id'], unique=False)
    op.create_index('ix_hot_topic_trends_hot_topic_id', 'hot_topic_trends', ['hot_topic_id'], unique=False)
    op.create_index('ix_hot_topic_trends_recorded_at', 'hot_topic_trends', ['recorded_at'], unique=False)
    op.create_index('idx_trend_topic', 'hot_topic_trends', ['hot_topic_id'], unique=False)
    op.create_index('idx_trend_recorded', 'hot_topic_trends', ['recorded_at'], unique=False)
    op.create_index('idx_trend_topic_time', 'hot_topic_trends', ['hot_topic_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hot_topic_trends')
    op.drop_table('contents')
    op.drop_table('token_blacklist')
    op.drop_table('push_records')
    op.drop_table('subscriptions')
    op.drop_table('user_personas')
    op.drop_table('tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
