"""add_calendar_events_table

Revision ID: fcf774614a16
Revises: d790408afca8
Create Date: 2026-06-24 07:38:53.765450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf774614a16'
down_revision: Union[str, None] = 'd790408afca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_user_date', 'calendar_events', ['user_id', 'scheduled_date'], unique=False)
    op.create_index('idx_calendar_user_status', 'calendar_events', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_calendar_events_content_ref_id'), 'calendar_events', ['content_ref_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_platform'), 'calendar_events', ['platform'], unique=False)
    op.create_index(op.f('ix_calendar_events_scheduled_date'), 'calendar_events', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_calendar_events_status'), 'calendar_events', ['status'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_status'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_scheduled_date'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_platform'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_content_ref_id'), table_name='calendar_events')
    op.drop_index('idx_calendar_user_status', table_name='calendar_events')
    op.drop_index('idx_calendar_user_date', table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
